# Generated by Django 5.2.13 on 2026-04-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_feedback_qa_pair_chatlog_canonicalqa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='운영자 식별용 이름 (예: "며칠 보강", "복지포인트 오분류 제외")', max_length=100)),
                ('route', models.CharField(choices=[('single_shot', 'single-shot'), ('workflow', 'workflow'), ('agent', 'agent')], help_text='매치 시 보낼 route', max_length=20)),
                ('match_type', models.CharField(choices=[('contains', '포함 (contains)')], default='contains', max_length=20)),
                ('pattern', models.CharField(help_text='매칭할 키워드/패턴 (match_type 에 따라 해석)', max_length=256)),
                ('priority', models.IntegerField(default=100, help_text='숫자가 클수록 먼저 평가. 기본값 100, 매우 중요한 rule 은 200+ 권장')),
                ('enabled', models.BooleanField(default=True, help_text='체크 해제하면 router 가 이 rule 을 건너뜀 (삭제 없이 무력화)')),
                ('description', models.TextField(blank=True, help_text='이 rule 을 추가한 이유·배경 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-updated_at'],
            },
        ),
    ]
