# Generated by Django 5.2.13 on 2026-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_routerrule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerrule',
            name='workflow_key',
            field=models.CharField(blank=True, default='', help_text='route 가 "workflow" 일 때만 의미가 있습니다.\n어떤 generic workflow 로 보낼지 선택하세요 (Phase 6 부터).\n비워두면 workflow 경로이더라도 기존처럼 single_shot 으로 응답합니다.', max_length=64),
        ),
    ]
