# Generated by Django 5.2.13 on 2026-04-28 06:24

import django.core.validators
from django.db import migrations, models


def _seed_singleton(apps, schema_editor):
    """Phase 8-3: AgentSettings 의 초기 1행 보장.

    `get_solo()` 가 첫 호출 시점에 자동 생성하지만, 마이그레이션 시점에 미리
    심어 두면 첫 BO GET 이전에 runtime 이 settings 를 조회해도 동일 default
    상태가 보장된다 — 모든 환경 (dev / test / production) 동일 시작점.
    """
    AgentSettings = apps.get_model('chat', 'AgentSettings')
    AgentSettings.objects.get_or_create(pk=1, defaults={
        'enabled': True,
        'max_iterations': 6,
        'max_low_relevance_retrieves': 3,
    })


def _noop_reverse(apps, schema_editor):
    # CreateModel 이 자동으로 테이블 drop 해주므로 별도 reverse 불필요.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_tokenusage_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='체크를 풀면 agent 경로 진입 시 single_shot 으로 폴백합니다 (incident 대응용 kill switch).')),
                ('max_iterations', models.PositiveSmallIntegerField(default=6, help_text='ReAct loop 의 최대 iteration 수 (1~12). 작을수록 응답 빠르고 비용 절감, 클수록 복잡한 비교 질문 처리 가능.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('max_low_relevance_retrieves', models.PositiveSmallIntegerField(default=3, help_text='retrieve_documents 의 low_relevance 누적 한도 (1~10). 도달하면 NOT_FOUND 로 종료해 무관 자료 무한 재검색 차단.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_iterations__gte', 1), ('max_iterations__lte', 12)), name='agentsettings_max_iterations_range'), models.CheckConstraint(condition=models.Q(('max_low_relevance_retrieves__gte', 1), ('max_low_relevance_retrieves__lte', 10)), name='agentsettings_max_low_relevance_range')],
            },
        ),
        migrations.RunPython(_seed_singleton, _noop_reverse),
    ]
