# Generated by Django 5.2.13 on 2026-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_agentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
