# Generated by Django 5.2.13 on 2026-04-29 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_tokenusage_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='max_consecutive_failures',
            field=models.PositiveSmallIntegerField(default=3, help_text='연속 실패 한도 (1~10). 도달 시 NO_MORE_USEFUL_TOOLS 종료.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='max_repeated_call',
            field=models.PositiveSmallIntegerField(default=3, help_text='동일 (tool, args) 반복 호출 한도 (2~10). ※ 현재는 8-3 의 즉시 차단 정책으로 동일 호출이 1회만 record 되어 본 값은 호환/기록용 — 변경해도 실제 동작 변화 거의 없음. 정책 통합은 후속 Phase.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='agentsettings',
            constraint=models.CheckConstraint(condition=models.Q(('max_consecutive_failures__gte', 1), ('max_consecutive_failures__lte', 10)), name='agentsettings_max_consecutive_failures_range'),
        ),
        migrations.AddConstraint(
            model_name='agentsettings',
            constraint=models.CheckConstraint(condition=models.Q(('max_repeated_call__gte', 2), ('max_repeated_call__lte', 10)), name='agentsettings_max_repeated_call_range'),
        ),
    ]
