# Generated by Django 5.1.15 on 2026-05-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_agentsettingsaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='normalized_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InputNormalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='치환할 입력 키 (예: "rudwhtk").\n저장 시 자동으로 NFKC + strip + casefold 가 적용됩니다.', max_length=200)),
                ('replacement', models.CharField(help_text='정규화 결과 (예: "경조사").\n운영자가 입력한 원형 그대로 사용됩니다 — casefold 등 변형 없음.', max_length=200)),
                ('match_type', models.CharField(choices=[('exact', '정확히 일치 (exact)'), ('contains', '포함 (contains)')], default='exact', help_text='• 정확히 일치 — canonical 입력 전체가 pattern 과 같을 때만 적용\n• 포함 — canonical 입력 안에 pattern 이 들어 있으면 첫 1회 치환\n※ contains 는 pattern 길이 2 이상만 허용 (과잉 적용 방지).', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='체크를 풀면 이 규칙을 무시합니다 (삭제하지 않고 잠시 꺼두는 용도).')),
                ('priority', models.PositiveIntegerField(default=100, help_text='숫자가 클수록 먼저 평가됩니다.\n동률이면 id ASC (먼저 등록된 규칙)가 우선.')),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(fields=['enabled', '-priority'], name='chat_inputn_enabled_4f1925_idx')],
                'constraints': [models.UniqueConstraint(fields=('pattern', 'match_type'), name='inputnorm_pattern_matchtype_unique')],
            },
        ),
    ]
