# Generated by Django 5.1.15 on 2026-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_input_normalization_and_chatlog_normalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_question', models.CharField(blank=True, max_length=500)),
                ('conversation', models.JSONField(default=list)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', '신규'), ('in_progress', '확인 중'), ('resolved', '해결'), ('wontfix', '보류')], db_index=True, default='open', max_length=16)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문제 제보',
                'ordering': ['-created_at'],
            },
        ),
    ]
